"""Compliance monitoring report PDF generation.

Generates a regulatory compliance report for a given framework and time period.
Sections: Cover, Executive Summary, Continuous Monitoring Status, Incident Log,
Regulatory Requirement Mapping, Recommendations, Appendix.
"""

import logging
import math
import os
import tempfile
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from fpdf import FPDF

from app.db import clickhouse, postgres
from app.reports.narrative import generate_narrative

logger = logging.getLogger("intelligence.reports.compliance")

REPORTS_DIR = os.environ.get("REPORTS_DIR", "/tmp/asb_reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

# ─── Constants ────────────────────────────────────────────────────────────────

FRAMEWORK_NAMES: dict[str, str] = {
    "EU_AI_ACT":   "EU AI Act (Regulation 2024/1689)",
    "ISO_10218":   "ISO 10218-1/2:2025 — Industrial Robot Safety",
    "OSHA":        "OSHA 1910.212 — Machine Guarding",
    "OSHA_1910":   "OSHA 1910.212 — Machine Guarding",
    "ANSI_R15_08": "ANSI/RIA R15.08 — Autonomous Mobile Robot Safety",
    "IEC_62443":   "IEC 62443-3-3 — Industrial Control System Security",
    "INTERNAL":    "Internal Safety Standard",
}

# PDF row fill colors (R, G, B) per severity
SEVERITY_ROW_COLORS: dict[str, tuple[int, int, int]] = {
    "CRITICAL": (255, 230, 230),
    "HIGH":     (255, 243, 220),
    "MEDIUM":   (255, 252, 220),
    "LOW":      (230, 255, 240),
}

# Text colors per severity
SEVERITY_TEXT_COLORS: dict[str, tuple[int, int, int]] = {
    "CRITICAL": (180, 0,   0),
    "HIGH":     (160, 80,  0),
    "MEDIUM":   (120, 100, 0),
    "LOW":      (0,   120, 50),
}

# Status badge colors
STATUS_COLORS: dict[str, tuple[int, int, int]] = {
    "met":     (0, 150, 80),
    "partial": (200, 120, 0),
    "not_met": (200, 40,  40),
}

# Monitoring uptime thresholds
UPTIME_MET     = 95.0   # ≥ this → "met"
UPTIME_PARTIAL = 50.0   # ≥ this → "partial"


# ─── PDF class ────────────────────────────────────────────────────────────────

class ComplianceReportPDF(FPDF):
    """FPDF subclass matching the dashboard design language from ReportPDF."""

    def __init__(self, facility_name: str, framework_display: str, period_str: str):
        super().__init__()
        self.facility_name = facility_name
        self.framework_display = framework_display
        self.period_str = period_str
        self.gen_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6,
            f"Compliance Report — {self.facility_name} — {self.period_str}",
            ln=True, align="L")
        self.line(10, 12, 200, 12)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5,
            f"Generated by AI Security Brain · {self.gen_time} · Page {self.page_no()}/{{nb}}",
            align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, title, ln=True)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def subsection_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 7, title, ln=True)
        self.ln(1)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def stat_row(self, label: str, value: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.cell(80, 6, label)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(30, 30, 30)
        self.cell(60, 6, value, ln=True)

    def table_header(self, cols: list[tuple[str, int]]):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(240, 240, 240)
        self.set_text_color(60, 60, 60)
        for label, width in cols:
            self.cell(width, 6, label, border=1, fill=True)
        self.ln()

    def table_row(
        self,
        cols: list[tuple[str, int]],
        fill_color: tuple[int, int, int] | None = None,
        text_color: tuple[int, int, int] | None = None,
    ):
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*(text_color or (40, 40, 40)))
        if fill_color:
            self.set_fill_color(*fill_color)
        for value, width in cols:
            self.cell(width, 5, _trunc(str(value), width), border=1, fill=bool(fill_color))
        self.ln()
        if fill_color:
            self.set_fill_color(255, 255, 255)
        if text_color:
            self.set_text_color(40, 40, 40)

    def status_cell(self, status: str, width: int = 22):
        """Inline colored status badge within a table row."""
        r, g, b = STATUS_COLORS.get(status, (100, 100, 100))
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(r, g, b)
        self.cell(width, 5, status.replace("_", " ").upper(), border=1)
        self.set_text_color(40, 40, 40)


# ─── Text helpers ─────────────────────────────────────────────────────────────

def _trunc(s: str, col_width: int, chars_per_mm: float = 0.45) -> str:
    """Truncate a string to fit in a PDF column of col_width mm."""
    max_chars = max(4, int(col_width * chars_per_mm))
    if len(s) <= max_chars:
        return s
    return s[: max_chars - 1] + "…"


def _fmt_dt(dt: Any) -> str:
    if dt is None:
        return "—"
    if isinstance(dt, datetime):
        return dt.strftime("%Y-%m-%d %H:%M")
    return str(dt)[:16]


# ─── DB helpers ───────────────────────────────────────────────────────────────

async def _get_reportable_incidents(
    facility_id: str, framework: str, start: datetime, end: datetime
) -> list[dict]:
    """Return incidents that are reportable under the given framework."""
    pool = await postgres.get_pool()

    if framework == "EU_AI_ACT":
        flag = "reportable_eu_ai_act = true"
        extra: list[Any] = []
    elif framework in ("OSHA", "OSHA_1910"):
        flag = "reportable_osha = true"
        extra = []
    else:
        flag = "regulatory_framework = $4"
        extra = [framework]

    q = f"""
        SELECT id, robot_id, event_type, severity, description,
               distance_cm, speed, occurred_at, created_at,
               COALESCE(safety_standard_ref, '')  AS safety_standard_ref,
               COALESCE(safety_clause, '')         AS safety_clause,
               COALESCE(regulatory_framework, '')  AS regulatory_framework,
               COALESCE(compliance_category, '')   AS compliance_category,
               COALESCE(reportable_eu_ai_act, false) AS reportable_eu_ai_act,
               COALESCE(reportable_osha, false)    AS reportable_osha,
               COALESCE(monitoring_requirement, '') AS monitoring_requirement,
               COALESCE(tags, ARRAY[]::TEXT[])     AS tags,
               root_cause
        FROM incidents
        WHERE facility_id = $1
          AND occurred_at >= $2
          AND occurred_at <= $3
          AND {flag}
        ORDER BY occurred_at DESC
    """
    rows = await pool.fetch(q, facility_id, start, end, *extra)
    return [dict(r) for r in rows]


async def _get_compliance_requirements(framework: str) -> list[dict]:
    """Return seeded compliance requirements for the given framework."""
    pool = await postgres.get_pool()
    rows = await pool.fetch(
        """
        SELECT id, framework, requirement_id, title,
               COALESCE(description, '')           AS description,
               COALESCE(monitoring_type, '')       AS monitoring_type,
               COALESCE(applicable_event_types, ARRAY[]::TEXT[]) AS applicable_event_types,
               COALESCE(severity_threshold, '')    AS severity_threshold,
               COALESCE(reporting_deadline, '')    AS reporting_deadline,
               active
        FROM compliance_requirements
        WHERE framework = $1 AND active = true
        ORDER BY requirement_id
        """,
        framework,
    )
    return [dict(r) for r in rows]


def _get_hourly_coverage(
    facility_id: str, start: datetime, end: datetime
) -> dict[datetime, int]:
    """
    Query ClickHouse for hourly telemetry event counts in the period.
    Returns {hour_start_utc: event_count}.
    """
    try:
        client = clickhouse.get_client()
        q = """
            SELECT toStartOfHour(timestamp) AS hr, count() AS cnt
            FROM telemetry
            WHERE facility_id = %(facility_id)s
              AND timestamp >= %(start)s
              AND timestamp <= %(end)s
            GROUP BY hr
            ORDER BY hr
        """
        result = client.query(q, parameters={
            "facility_id": facility_id, "start": start, "end": end,
        })
        out: dict[datetime, int] = {}
        for row in result.result_rows:
            hr = row[0]
            if isinstance(hr, datetime) and hr.tzinfo is None:
                hr = hr.replace(tzinfo=timezone.utc)
            out[hr] = int(row[1])
        return out
    except Exception as exc:
        logger.warning(f"ClickHouse hourly coverage query failed: {exc}")
        return {}


def _get_total_telemetry_events(
    facility_id: str, start: datetime, end: datetime
) -> int:
    """Total telemetry event count in the period."""
    try:
        client = clickhouse.get_client()
        result = client.query(
            """SELECT count() FROM telemetry
               WHERE facility_id = %(fid)s AND timestamp >= %(s)s AND timestamp <= %(e)s""",
            parameters={"fid": facility_id, "s": start, "e": end},
        )
        if result.result_rows:
            return int(result.result_rows[0][0])
    except Exception as exc:
        logger.warning(f"ClickHouse event count failed: {exc}")
    return 0


# ─── Chart helper ─────────────────────────────────────────────────────────────

def _render_uptime_chart(
    hourly_coverage: dict[datetime, int],
    start: datetime,
    end: datetime,
) -> str | None:
    """
    Render a daily-aggregated monitoring uptime bar chart.
    Each bar = percentage of hours with telemetry data in that day.
    Returns the path to a temporary PNG, or None on failure.
    """
    try:
        # Bucket hourly coverage into days
        day_totals: dict[date, int] = defaultdict(int)  # total hours in day
        day_active: dict[date, int] = defaultdict(int)  # hours with data

        current = start.replace(minute=0, second=0, microsecond=0)
        while current < end:
            day = current.date()
            day_totals[day] += 1
            h = current
            # Normalize ClickHouse result keys (may be naive or aware)
            h_naive = h.replace(tzinfo=None) if h.tzinfo else h
            for k in hourly_coverage:
                k_naive = k.replace(tzinfo=None) if hasattr(k, "tzinfo") and k.tzinfo else k
                if k_naive.date() == h_naive.date() and k_naive.hour == h_naive.hour:
                    day_active[day] += 1
                    break
            current += timedelta(hours=1)

        days = sorted(day_totals.keys())
        if not days:
            return None

        uptime_vals = [
            day_active[d] / day_totals[d] * 100 if day_totals[d] > 0 else 0
            for d in days
        ]
        bar_colors = [
            "#00C9A7" if v >= UPTIME_MET else ("#F59E0B" if v >= UPTIME_PARTIAL else "#EF4444")
            for v in uptime_vals
        ]

        fig, ax = plt.subplots(figsize=(12, 2.5))
        ax.set_facecolor("#111827")
        fig.patch.set_facecolor("#0B0F19")

        ax.bar(range(len(days)), uptime_vals, color=bar_colors, width=0.85, edgecolor="none")
        ax.axhline(y=UPTIME_MET, color="#64748B", linewidth=0.7, linestyle="--", label=f"{UPTIME_MET:.0f}% threshold")
        ax.set_ylim(0, 110)
        ax.set_xlim(-0.5, len(days) - 0.5)
        ax.set_ylabel("Uptime %", color="#64748B", fontsize=7)
        ax.tick_params(colors="#64748B", labelsize=6)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        for spine in ("left", "bottom"):
            ax.spines[spine].set_color("#1E293B")

        # X labels — show every Nth day to avoid crowding
        step = max(1, math.ceil(len(days) / 15))
        ax.set_xticks(range(0, len(days), step))
        ax.set_xticklabels(
            [days[i].strftime("%b %d") for i in range(0, len(days), step)],
            color="#64748B", fontsize=6,
        )

        legend_handles = [
            mpatches.Patch(color="#00C9A7", label=f"≥{UPTIME_MET:.0f}% — Met"),
            mpatches.Patch(color="#F59E0B", label=f"≥{UPTIME_PARTIAL:.0f}% — Partial"),
            mpatches.Patch(color="#EF4444", label=f"<{UPTIME_PARTIAL:.0f}% — Not met"),
        ]
        ax.legend(handles=legend_handles, loc="upper right", fontsize=6,
                  facecolor="#111827", edgecolor="#1E293B", labelcolor="#E8ECF1")

        ax.set_title("Daily Monitoring Uptime", color="#E8ECF1", fontsize=8, pad=6)
        fig.tight_layout(pad=0.5)

        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        fig.savefig(tmp.name, dpi=120, bbox_inches="tight", facecolor=fig.get_facecolor())
        plt.close(fig)
        return tmp.name

    except Exception as exc:
        logger.warning(f"Failed to render uptime chart: {exc}")
        return None


# ─── Requirement status ───────────────────────────────────────────────────────

def _requirement_status(
    req: dict,
    all_incidents: list[dict],
    uptime_pct: float,
) -> tuple[str, int, str | None]:
    """
    Returns (status, matching_event_count, last_occurrence_str).

    Status logic:
    - continuous:     met ≥ 95% uptime, partial ≥ 50%, not_met < 50%
    - event_triggered: met if events captured OR no trigger occurred (monitoring active);
                       not_met if monitoring is down (no telemetry at all)
    - periodic:       met ≥ 50% uptime, partial if any uptime, not_met = zero uptime
    """
    applicable = req.get("applicable_event_types") or []
    matching = [i for i in all_incidents if i.get("event_type") in applicable]
    count = len(matching)
    last = None
    if matching:
        latest = max(matching, key=lambda i: i["occurred_at"])
        last = _fmt_dt(latest["occurred_at"])

    mtype = req.get("monitoring_type", "continuous")

    if mtype == "event_triggered":
        if uptime_pct > 0:
            status = "met"       # infrastructure is running; events captured if they occurred
        else:
            status = "not_met"   # no telemetry at all — cannot verify
    elif mtype == "continuous":
        if uptime_pct >= UPTIME_MET:
            status = "met"
        elif uptime_pct >= UPTIME_PARTIAL:
            status = "partial"
        else:
            status = "not_met"
    else:  # periodic
        if uptime_pct >= UPTIME_PARTIAL:
            status = "met"
        elif uptime_pct > 0:
            status = "partial"
        else:
            status = "not_met"

    return status, count, last


# ─── Main function ────────────────────────────────────────────────────────────

async def generate_compliance_report(
    facility_id: str,
    framework: str,
    start_date: date,
    end_date: date,
) -> str:
    """
    Generate a compliance monitoring PDF for the given framework and period.
    Returns the local filepath of the generated PDF.
    """
    framework = framework.upper()
    framework_display = FRAMEWORK_NAMES.get(framework, framework)
    period_str = f"{start_date.isoformat()} to {end_date.isoformat()}"

    logger.info(f"[{facility_id}] generating compliance report: {framework} {period_str}")

    # Convert dates to UTC datetimes for DB queries
    start_dt = datetime.combine(start_date, datetime.min.time()).replace(tzinfo=timezone.utc)
    end_dt = datetime.combine(end_date, datetime.max.time()).replace(tzinfo=timezone.utc)

    # ── Resolve facility name ─────────────────────────────────────────────────
    facility_name = facility_id
    try:
        facilities = await postgres.get_facilities()
        for f in facilities:
            if f["id"] == facility_id:
                facility_name = f["name"]
                break
    except Exception as exc:
        logger.warning(f"Could not resolve facility name: {exc}")

    # ── Gather data ───────────────────────────────────────────────────────────
    all_incidents = await postgres.get_incidents(
        facility_id=facility_id, since=start_dt, until=end_dt, limit=10_000
    )
    reportable_incidents = await _get_reportable_incidents(
        facility_id, framework, start_dt, end_dt
    )
    requirements = await _get_compliance_requirements(framework)
    hourly_coverage = _get_hourly_coverage(facility_id, start_dt, end_dt)
    total_telemetry_events = _get_total_telemetry_events(facility_id, start_dt, end_dt)
    active_robots = clickhouse.get_robots_active_today(facility_id, start_dt, end_dt)

    # ── Compute monitoring stats ──────────────────────────────────────────────
    total_hours = max(1, math.ceil((end_dt - start_dt).total_seconds() / 3600))
    hours_with_data = len(hourly_coverage)
    uptime_pct = (hours_with_data / total_hours) * 100
    avg_freq_hz = (total_telemetry_events / max(hours_with_data * 3600, 1))

    # Find monitoring gaps: windows of consecutive missing hours ≥ 1 h
    gaps: list[dict] = []
    curr = start_dt.replace(minute=0, second=0, microsecond=0)
    gap_start: datetime | None = None

    # Build a normalized set of covered hours for gap detection
    covered = set()
    for h in hourly_coverage:
        covered.add(h.replace(tzinfo=timezone.utc) if h.tzinfo is None else h)

    while curr < end_dt:
        curr_utc = curr.replace(tzinfo=timezone.utc) if curr.tzinfo is None else curr
        has_data = any(
            abs((k - curr_utc).total_seconds()) < 1800 for k in covered
        )
        if not has_data:
            if gap_start is None:
                gap_start = curr
        else:
            if gap_start is not None:
                gap_hours = (curr - gap_start).total_seconds() / 3600
                gaps.append({
                    "start": gap_start,
                    "end": curr,
                    "duration_hours": gap_hours,
                })
                gap_start = None
        curr += timedelta(hours=1)

    if gap_start is not None:
        gap_hours = (end_dt - gap_start).total_seconds() / 3600
        gaps.append({"start": gap_start, "end": end_dt, "duration_hours": gap_hours})

    significant_gaps = [g for g in gaps if g["duration_hours"] >= 1.0]

    # ── Compute compliance score ──────────────────────────────────────────────
    classified_count = sum(
        1 for i in all_incidents if i.get("regulatory_framework")
    )
    classification_rate = (classified_count / max(len(all_incidents), 1)) * 100
    # 70% weight on monitoring uptime, 30% on incident classification coverage
    compliance_score = uptime_pct * 0.7 + classification_rate * 0.3

    # ── Requirement status mapping ────────────────────────────────────────────
    req_statuses: list[dict] = []
    for req in requirements:
        status, ev_count, last_occ = _requirement_status(req, all_incidents, uptime_pct)
        req_statuses.append({
            **req,
            "status": status,
            "event_count": ev_count,
            "last_occurrence": last_occ,
        })

    not_met_reqs  = [r for r in req_statuses if r["status"] == "not_met"]
    partial_reqs  = [r for r in req_statuses if r["status"] == "partial"]

    # ── Compute recommendations ───────────────────────────────────────────────
    recommendations: list[str] = []

    for r in not_met_reqs:
        recommendations.append(
            f"[{r['requirement_id']}] {r['title']}: requirement is NOT MET (zero monitoring "
            f"coverage detected). Deploy or reconnect robot telemetry and verify that events "
            f"matching {r.get('applicable_event_types') or 'this requirement'} are being classified."
        )

    for r in partial_reqs:
        recommendations.append(
            f"[{r['requirement_id']}] {r['title']}: requirement is PARTIAL ({uptime_pct:.0f}% "
            f"uptime). Investigate monitoring gaps and work toward ≥{UPTIME_MET:.0f}% coverage."
        )

    if uptime_pct < UPTIME_MET and not not_met_reqs and not partial_reqs:
        recommendations.append(
            f"Overall telemetry uptime is {uptime_pct:.1f}%, below the {UPTIME_MET:.0f}% "
            f"threshold. Review robot connectivity, network reliability, and watchdog settings."
        )

    if significant_gaps:
        longest = max(significant_gaps, key=lambda g: g["duration_hours"])
        recommendations.append(
            f"{len(significant_gaps)} monitoring gap(s) detected "
            f"(longest: {longest['duration_hours']:.1f}h starting "
            f"{_fmt_dt(longest['start'])}). Consider alerting on gaps > 5 minutes."
        )

    # Threshold adjustment hints based on incident distribution
    type_counts: dict[str, int] = defaultdict(int)
    for inc in reportable_incidents:
        type_counts[inc.get("event_type", "UNKNOWN")] += 1

    if type_counts.get("PROXIMITY_ALERT", 0) > 10:
        recommendations.append(
            f"{type_counts['PROXIMITY_ALERT']} proximity alerts recorded. Consider raising the "
            "proximity threshold or reconfiguring operating zones to reduce frequent low-severity triggers."
        )
    if type_counts.get("SPEED_VIOLATION", 0) > 5:
        recommendations.append(
            f"{type_counts['SPEED_VIOLATION']} speed violations recorded. Review speed limits "
            "per zone and ensure all robots have zone-aware speed profiles configured."
        )

    if not recommendations:
        recommendations.append(
            "All regulatory requirements are fully met for this period. "
            "Continue current monitoring practices."
        )

    # ── Generate narratives ───────────────────────────────────────────────────
    exec_narrative = await generate_narrative(
        "compliance_executive_summary",
        framework=framework_display,
        facility=facility_name,
        period=period_str,
        total_incidents=len(all_incidents),
        reportable_count=len(reportable_incidents),
        compliance_score=round(compliance_score, 1),
        uptime_pct=round(uptime_pct, 1),
        active_robots=len(active_robots),
        not_met_count=len(not_met_reqs),
    )
    rec_narrative = await generate_narrative(
        "compliance_recommendations",
        framework=framework_display,
        uptime_pct=round(uptime_pct, 1),
        not_met_count=len(not_met_reqs),
        partial_count=len(partial_reqs),
        gap_count=len(significant_gaps),
        top_event_types=dict(sorted(type_counts.items(), key=lambda x: -x[1])[:3]),
    )

    # ─────────────────────────────────────────────────────────────────────────
    # Build PDF
    # ─────────────────────────────────────────────────────────────────────────
    pdf = ComplianceReportPDF(facility_name, framework_display, period_str)
    pdf.alias_nb_pages()

    # ── 1. Cover page ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(11, 15, 25)
    pdf.rect(0, 0, 210, 55, "F")
    pdf.set_text_color(0, 201, 167)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(15, 10)
    pdf.cell(0, 10, "AI Security Brain")
    pdf.set_text_color(232, 236, 241)
    pdf.set_font("Helvetica", "", 13)
    pdf.set_xy(15, 24)
    pdf.cell(0, 8, "Compliance Monitoring Report")
    pdf.set_text_color(0, 201, 167)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_xy(15, 36)
    pdf.cell(0, 7, framework_display)

    pdf.set_text_color(60, 60, 60)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_xy(15, 68)
    pdf.cell(0, 7, f"Facility:          {facility_name}", ln=True)
    pdf.set_x(15)
    pdf.cell(0, 7, f"Reporting period:  {period_str}", ln=True)
    pdf.set_x(15)
    pdf.cell(0, 7, f"Generated:         {pdf.gen_time}", ln=True)

    # Compliance score summary box
    score_color = (0, 150, 80) if compliance_score >= 90 else \
                  (200, 120, 0) if compliance_score >= 60 else (200, 40, 40)
    pdf.set_xy(15, 105)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 7, f"Compliance Score: {compliance_score:.1f}%", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Monitoring uptime: {uptime_pct:.1f}%  |  "
                   f"Reportable incidents: {len(reportable_incidents)}  |  "
                   f"Active robots: {len(active_robots)}", ln=True)

    # ── 2. Executive Summary ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Executive Summary")

    pdf.stat_row("Regulatory Framework",    framework_display[:60])
    pdf.stat_row("Total Incidents",         str(len(all_incidents)))
    pdf.stat_row("Reportable Incidents",    str(len(reportable_incidents)))
    pdf.stat_row("Compliance Score",        f"{compliance_score:.1f}%")
    pdf.stat_row("Monitoring Uptime",       f"{uptime_pct:.1f}%  ({hours_with_data}/{total_hours} hours)")
    pdf.stat_row("Active Robots Monitored", str(len(active_robots)))
    pdf.stat_row("Requirements Met",
        f"{sum(1 for r in req_statuses if r['status'] == 'met')} / {len(req_statuses)}")
    pdf.stat_row("Requirements Partially Met",
        str(sum(1 for r in req_statuses if r["status"] == "partial")))
    pdf.stat_row("Requirements Not Met",    str(len(not_met_reqs)))
    pdf.ln(4)

    pdf.body_text(exec_narrative)

    # ── 3. Continuous Monitoring Status ──────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Continuous Monitoring Status")

    pdf.subsection_title("Telemetry Coverage")
    pdf.stat_row("Total period hours",       f"{total_hours}")
    pdf.stat_row("Hours with telemetry",     f"{hours_with_data}")
    pdf.stat_row("Uptime percentage",        f"{uptime_pct:.1f}%")
    pdf.stat_row("Total telemetry events",   f"{total_telemetry_events:,}")
    pdf.stat_row("Average telemetry freq",   f"{avg_freq_hz:.2f} Hz")
    pdf.ln(3)

    pdf.subsection_title("Robots Monitored")
    if active_robots:
        pdf.body_text("  •  " + "\n  •  ".join(active_robots[:20]))
    else:
        pdf.body_text("No robot telemetry received in this period.")
    pdf.ln(2)

    pdf.subsection_title("Monitoring Gaps")
    if significant_gaps:
        cols = [("Start", 55), ("End", 55), ("Duration (hours)", 40)]
        pdf.table_header(cols)
        for g in significant_gaps[:30]:
            pdf.table_row([
                (_fmt_dt(g["start"]), 55),
                (_fmt_dt(g["end"]),   55),
                (f"{g['duration_hours']:.1f}", 40),
            ])
        if len(significant_gaps) > 30:
            pdf.body_text(f"  … and {len(significant_gaps) - 30} additional gaps (see Appendix).")
    else:
        pdf.body_text("No monitoring gaps detected. Coverage was continuous throughout the period.")

    # ── 4. Incident Log ───────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title(f"Incident Log — Reportable Events ({framework})")

    if not reportable_incidents:
        pdf.body_text(
            f"No incidents reportable under {framework_display} were recorded in this period. "
            "This indicates that no threshold-crossing events requiring external reporting occurred."
        )
    else:
        cols = [
            ("Timestamp",   36),
            ("Robot",       24),
            ("Type",        32),
            ("Severity",    18),
            ("Standard",    38),
            ("Description", 42),
        ]
        pdf.table_header(cols)
        rows_per_page = 28

        for idx, inc in enumerate(reportable_incidents):
            if idx > 0 and idx % rows_per_page == 0:
                pdf.add_page()
                pdf.section_title(f"Incident Log (continued)")
                pdf.table_header(cols)

            sev = inc.get("severity", "")
            fill = SEVERITY_ROW_COLORS.get(sev)
            pdf.table_row([
                (_fmt_dt(inc.get("occurred_at")),            36),
                (inc.get("robot_id", "—"),                   24),
                (inc.get("event_type", "—"),                 32),
                (sev,                                        18),
                (inc.get("safety_standard_ref", "—"),        38),
                (inc.get("description", "—"),                42),
            ], fill_color=fill)

    # ── 5. Regulatory Requirement Mapping ─────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Regulatory Requirement Mapping")

    if not req_statuses:
        pdf.body_text(f"No requirements found for framework {framework}. "
                      "Ensure the compliance_requirements table has been seeded.")
    else:
        for rs in req_statuses:
            # Check space before starting a requirement block
            if pdf.get_y() > 240:
                pdf.add_page()

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 6, f"[{rs['requirement_id']}] {rs['title']}", ln=True)

            # Status badge + monitoring type inline
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(35, 5, "Status:")
            pdf.status_cell(rs["status"], width=22)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(40, 5, f"  Monitoring: {rs.get('monitoring_type', '—')}")
            if rs.get("reporting_deadline"):
                pdf.cell(0, 5, f"  Deadline: {rs['reporting_deadline']}")
            pdf.ln()

            # Evidence
            ev_str = f"{rs['event_count']} matching event(s)"
            if rs["last_occurrence"]:
                ev_str += f", most recent: {rs['last_occurrence']}"
            else:
                ev_str += " (none in period)"
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(35, 5, "Evidence:")
            pdf.cell(0, 5, ev_str, ln=True)

            # Applicable event types
            types = rs.get("applicable_event_types") or []
            if types:
                pdf.cell(35, 5, "Event types:")
                pdf.cell(0, 5, ", ".join(types), ln=True)

            pdf.set_draw_color(220, 220, 220)
            pdf.line(10, pdf.get_y() + 1, 200, pdf.get_y() + 1)
            pdf.ln(4)

    # ── 6. Recommendations ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Recommendations")

    pdf.body_text(rec_narrative)
    pdf.ln(2)

    for i, rec in enumerate(recommendations, 1):
        if pdf.get_y() > 250:
            pdf.add_page()
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(8, 6, f"{i}.")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 5, rec)
        pdf.ln(2)

    # ── 7. Appendix ───────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Appendix A — Monitoring Uptime Chart")

    chart_path = _render_uptime_chart(hourly_coverage, start_dt, end_dt)
    if chart_path and os.path.exists(chart_path):
        pdf.image(chart_path, x=10, w=190)
        pdf.ln(4)
        try:
            os.unlink(chart_path)
        except OSError:
            pass
    else:
        pdf.body_text("Uptime chart could not be generated (no telemetry data or rendering error).")

    pdf.add_page()
    pdf.section_title("Appendix B — All Incidents in Period")

    if not all_incidents:
        pdf.body_text("No incidents recorded in this period.")
    else:
        app_cols = [
            ("Timestamp",  36),
            ("Robot",      24),
            ("Type",       32),
            ("Severity",   18),
            ("Category",   28),
            ("Reportable", 22),
            ("Description",30),
        ]
        pdf.table_header(app_cols)
        rows_per_page = 30

        for idx, inc in enumerate(all_incidents):
            if idx > 0 and idx % rows_per_page == 0:
                pdf.add_page()
                pdf.section_title("Appendix B (continued)")
                pdf.table_header(app_cols)

            sev = inc.get("severity", "")
            reportable_flag = []
            if inc.get("reportable_eu_ai_act"):
                reportable_flag.append("EU")
            if inc.get("reportable_osha"):
                reportable_flag.append("OSHA")
            reportable_str = ", ".join(reportable_flag) if reportable_flag else "—"

            pdf.table_row([
                (_fmt_dt(inc.get("occurred_at")),            36),
                (inc.get("robot_id", "—"),                   24),
                (inc.get("event_type", "—"),                 32),
                (sev,                                        18),
                (inc.get("compliance_category") or "—",      28),
                (reportable_str,                             22),
                (inc.get("description", "—"),                30),
            ], fill_color=SEVERITY_ROW_COLORS.get(sev))

    # ─────────────────────────────────────────────────────────────────────────
    # Save PDF
    # ─────────────────────────────────────────────────────────────────────────
    filename = f"compliance_{framework.lower()}_{facility_id}_{start_date}_{end_date}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    logger.info(f"[{facility_id}] compliance report saved: {filepath}")

    # Upsert into compliance_reports table for record-keeping
    try:
        pool = await postgres.get_pool()
        await pool.execute(
            """
            INSERT INTO compliance_reports
                (facility_id, report_type, period_start, period_end,
                 total_incidents, reportable_incidents, compliance_score,
                 findings, recommendations, report_url)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
            ON CONFLICT (facility_id, report_type, period_start)
            DO UPDATE SET
                period_end           = EXCLUDED.period_end,
                total_incidents      = EXCLUDED.total_incidents,
                reportable_incidents = EXCLUDED.reportable_incidents,
                compliance_score     = EXCLUDED.compliance_score,
                findings             = EXCLUDED.findings,
                recommendations      = EXCLUDED.recommendations,
                report_url           = EXCLUDED.report_url,
                generated_at         = now()
            """,
            facility_id,
            framework,
            start_date,
            end_date,
            len(all_incidents),
            len(reportable_incidents),
            round(compliance_score, 2),
            _summary_findings_json(req_statuses, uptime_pct, len(significant_gaps)),
            _recommendations_json(recommendations),
            filepath,
        )
    except Exception as exc:
        logger.warning(f"Failed to upsert compliance_reports record: {exc}")

    return filepath


# ─── JSON helpers for DB upsert ───────────────────────────────────────────────

def _summary_findings_json(
    req_statuses: list[dict], uptime_pct: float, gap_count: int
) -> str:
    import json
    return json.dumps({
        "uptime_pct": round(uptime_pct, 1),
        "gap_count": gap_count,
        "requirements": [
            {
                "id": r["requirement_id"],
                "title": r["title"],
                "status": r["status"],
                "event_count": r["event_count"],
            }
            for r in req_statuses
        ],
    })


def _recommendations_json(recommendations: list[str]) -> str:
    import json
    return json.dumps([{"text": r} for r in recommendations])
