"""Monthly PDF report generation — 9-section safety & optimization report.

Sections: Cover, Executive Summary, Hotspot Analysis, Temporal Patterns,
Robot Health, Sensor/Hallucination, Root Cause Breakdown, Recommendations,
Month-over-Month Comparison.
"""

import logging
import os
from collections import Counter
from datetime import datetime, timedelta

from fpdf import FPDF

from app.db import clickhouse, postgres
from app.analysis.productivity import calculate_productivity
from app.reports.narrative import generate_narrative
from app.reports import charts

logger = logging.getLogger("intelligence.reports.generator")

REPORTS_DIR = os.environ.get("REPORTS_DIR", "/tmp/asb_reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


class ReportPDF(FPDF):
    """Custom PDF with header/footer styling."""

    def __init__(self, facility_name: str, month_str: str):
        super().__init__()
        self.facility_name = facility_name
        self.month_str = month_str
        self.gen_time = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return  # cover page has custom header
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, f"AI Security Brain — {self.facility_name} — {self.month_str}", ln=True, align="L")
        self.line(10, 12, 200, 12)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f"Generated by AI Security Brain · {self.gen_time} · Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, title, ln=True)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def stat_row(self, label: str, value: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.cell(70, 6, label)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(30, 30, 30)
        self.cell(60, 6, value, ln=True)

    def table_header(self, cols: list[tuple[str, int]]):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(240, 240, 240)
        self.set_text_color(60, 60, 60)
        for label, width in cols:
            self.cell(width, 6, label, border=1, fill=True)
        self.ln()

    def table_row(self, cols: list[tuple[str, int]]):
        self.set_font("Helvetica", "", 8)
        self.set_text_color(40, 40, 40)
        for value, width in cols:
            self.cell(width, 5, str(value)[:int(width / 2)], border=1)
        self.ln()


async def generate_monthly_pdf(facility_id: str, month_str: str) -> str | None:
    """Generate a full monthly safety report PDF. Returns local file path."""
    logger.info(f"[{facility_id}] generating monthly report for {month_str}")

    # Parse month
    try:
        month_date = datetime.strptime(month_str, "%Y-%m").date().replace(day=1)
    except ValueError:
        logger.error(f"Invalid month format: {month_str}")
        return None

    next_month = (month_date.replace(day=28) + timedelta(days=4)).replace(day=1)
    month_start = datetime.combine(month_date, datetime.min.time())
    month_end = datetime.combine(next_month, datetime.min.time())
    prev_month_start = (month_date - timedelta(days=1)).replace(day=1)
    prev_start = datetime.combine(prev_month_start, datetime.min.time())

    # Get facility name
    facilities = await postgres.get_facilities()
    facility_name = facility_id
    for f in facilities:
        if f["id"] == facility_id:
            facility_name = f["name"]
            break

    display_month = month_date.strftime("%B %Y")

    # Gather data
    incidents = await postgres.get_incidents(facility_id=facility_id, since=month_start, until=month_end)
    prev_incidents = await postgres.get_incidents(facility_id=facility_id, since=prev_start, until=month_start)
    hotspots = await postgres.get_hotspots(facility_id)
    patterns = await postgres.get_patterns(facility_id)
    health_scores = await postgres.get_latest_robot_health(facility_id)
    recommendations = await postgres.get_recommendations(facility_id, status="open")

    # Productivity metrics
    hours = int((month_end - month_start).total_seconds() / 3600)
    productivity = await calculate_productivity(facility_id, hours=hours)

    total = len(incidents)
    prev_total = len(prev_incidents)
    hallucinations = sum(1 for i in incidents if i.get("is_hallucination"))
    real = total - hallucinations

    # ─── Build PDF ───────────────────────────────────────────────────────────
    pdf = ReportPDF(facility_name, display_month)
    pdf.alias_nb_pages()

    # 1. COVER PAGE
    pdf.add_page()
    pdf.set_fill_color(11, 15, 25)
    pdf.rect(0, 0, 210, 50, "F")
    pdf.set_text_color(0, 201, 167)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_xy(15, 12)
    pdf.cell(0, 10, "AI Security Brain")
    pdf.set_text_color(232, 236, 241)
    pdf.set_font("Helvetica", "", 14)
    pdf.set_xy(15, 26)
    pdf.cell(0, 8, "Monthly Safety & Optimization Report")
    pdf.set_text_color(60, 60, 60)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_xy(15, 65)
    pdf.cell(0, 7, f"Facility: {facility_name}", ln=True)
    pdf.cell(0, 7, f"Period: {display_month}", ln=True)
    pdf.cell(0, 7, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)

    # 2. EXECUTIVE SUMMARY
    pdf.add_page()
    pdf.section_title("Executive Summary")

    trend = "Improving" if total < prev_total else ("Stable" if total == prev_total else "Declining")
    delta = abs(total - prev_total)
    arrow = "↓" if total < prev_total else ("→" if total == prev_total else "↑")

    pdf.stat_row("Total Incidents", f"{total} ({arrow} {delta} vs last month)")
    pdf.stat_row("Real Incidents", f"{real} ({hallucinations} hallucinations excluded)")
    pdf.stat_row("Hours Lost", f"{productivity['total_time_lost_hours']:.1f}")
    pdf.stat_row("Fleet Efficiency", f"{productivity['fleet_efficiency_pct']:.1f}%")
    pdf.stat_row("Overall Trend", trend)
    pdf.ln(4)

    summary = await generate_narrative(
        "executive_summary",
        total_incidents=total, prev_incidents=prev_total,
        fleet_efficiency_pct=productivity["fleet_efficiency_pct"],
        total_time_lost_hours=productivity["total_time_lost_hours"],
        hallucination_count=hallucinations, trend=trend,
    )
    pdf.body_text(summary)

    # 3. HOTSPOT ANALYSIS
    pdf.add_page()
    pdf.section_title("Hotspot Analysis")

    if hotspots:
        scatter_path = charts.render_incident_scatter(incidents, hotspots[:5])
        if scatter_path and os.path.exists(scatter_path):
            pdf.image(scatter_path, x=10, w=190)
            pdf.ln(4)
            os.unlink(scatter_path)

        for i, hs in enumerate(hotspots[:5]):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 6, f"Hotspot {i+1}: ({hs['center_x']:.1f}, {hs['center_y']:.1f})", ln=True)
            pdf.stat_row("  Incidents", str(hs.get("incident_count", 0)))
            pdf.stat_row("  Dominant Type", hs.get("dominant_type", "mixed"))
            pdf.stat_row("  Time Lost", f"{hs.get('time_lost_hours', 0):.1f} hours")
            pdf.stat_row("  Root Cause", hs.get("dominant_cause") or "various")
            pdf.body_text(f"  Recommendation: {hs.get('recommendation', 'N/A')}")
            pdf.stat_row("  Projected Savings", f"{hs.get('projected_savings_hours', 0):.1f} hours/month")
            pdf.ln(2)
    else:
        pdf.body_text("No spatial hotspots detected this period.")

    # 4. TEMPORAL PATTERNS
    pdf.add_page()
    pdf.section_title("Temporal Patterns")

    hourly_path = charts.render_hourly_histogram(incidents, patterns)
    if hourly_path and os.path.exists(hourly_path):
        pdf.image(hourly_path, x=10, w=190)
        pdf.ln(4)
        os.unlink(hourly_path)

    if patterns:
        for pat in patterns[:5]:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, pat.get("description", "")[:90], ln=True)
            pdf.body_text(f"  Recommendation: {pat.get('recommendation', 'N/A')}")
    else:
        pdf.body_text("No significant temporal patterns detected.")

    # 5. ROBOT HEALTH
    pdf.add_page()
    pdf.section_title("Robot Health Report")

    if health_scores:
        cols = [("Robot", 30), ("Score", 15), ("Inc/hr", 18), ("Sensor %", 20), ("Battery", 18), ("Flags", 55)]
        pdf.table_header(cols)
        for h in sorted(health_scores, key=lambda x: x.get("overall_score", 100)):
            flags = ", ".join(h.get("flags") or []) or "—"
            pdf.table_row([
                (h.get("robot_id", ""), 30),
                (f"{h.get('overall_score', 0):.0f}", 15),
                (f"{h.get('incidents_per_hour', 0):.2f}", 18),
                (f"{h.get('sensor_reliability_pct', 0):.1f}", 20),
                (f"{h.get('battery_avg_voltage', 0):.1f}V", 18),
                (flags[:30], 55),
            ])
        pdf.ln(4)

        # Battery trend charts for degrading robots
        for h in health_scores:
            if "battery_degrading" in (h.get("flags") or []):
                daily = clickhouse.get_daily_battery_avg(h["robot_id"], days=30)
                if daily:
                    path = charts.render_battery_trend(h["robot_id"], daily)
                    if path and os.path.exists(path):
                        pdf.image(path, x=10, w=140)
                        pdf.ln(2)
                        os.unlink(path)
    else:
        pdf.body_text("No robot health data available.")

    # 6. SENSOR & HALLUCINATION
    pdf.section_title("Sensor & Hallucination Report")
    pdf.stat_row("Total Hallucinations", str(hallucinations))
    if hallucinations > 0:
        hall_robots = Counter(
            i.get("robot_id", "") for i in incidents if i.get("is_hallucination")
        )
        top_hall = hall_robots.most_common(3)
        pdf.stat_row("Most Affected Robots", ", ".join(f"{r}({c})" for r, c in top_hall))
        pdf.body_text(
            f"Hallucinated events represent {hallucinations/max(total,1)*100:.1f}% of total incidents. "
            "These are excluded from productivity calculations. Sensor calibration is recommended "
            "for the most affected robots."
        )
    else:
        pdf.body_text("No sensor hallucinations detected this period. Sensor health is good.")

    # 7. ROOT CAUSE BREAKDOWN
    pdf.add_page()
    pdf.section_title("Root Cause Breakdown")

    pie_path = charts.render_root_cause_pie(incidents)
    if pie_path and os.path.exists(pie_path):
        pdf.image(pie_path, x=30, w=100)
        pdf.ln(4)
        os.unlink(pie_path)

    cause_counts = Counter(i.get("root_cause") or "unknown" for i in incidents if not i.get("is_hallucination"))
    if cause_counts:
        cols = [("Root Cause", 50), ("Count", 20), ("Percentage", 25)]
        pdf.table_header(cols)
        for cause, count in cause_counts.most_common():
            pct = f"{count / max(real, 1) * 100:.1f}%"
            pdf.table_row([(cause.replace("_", " ").title(), 50), (str(count), 20), (pct, 25)])

    # 8. RECOMMENDATIONS
    pdf.add_page()
    pdf.section_title("Recommendations")

    if recommendations:
        for i, rec in enumerate(recommendations[:10]):
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, f"{i+1}. {rec.get('title', '')}", ln=True)
            pdf.body_text(rec.get("description", ""))
            savings = rec.get("projected_time_saved_hours", 0)
            cost = rec.get("projected_cost_saved", 0)
            payback = rec.get("payback_days", 0)
            if savings > 0:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(80, 80, 80)
                pdf.cell(0, 4, f"   Projected savings: {savings:.1f}h/month (${cost:.0f}) · Payback: {payback:.0f} days", ln=True)
            pdf.ln(2)
    else:
        pdf.body_text("No open recommendations. All previous recommendations have been addressed.")

    # 9. MONTH-OVER-MONTH COMPARISON
    pdf.add_page()
    pdf.section_title("Month-over-Month Comparison")

    cols = [("Metric", 50), ("This Month", 35), ("Last Month", 35), ("Change", 30)]
    pdf.table_header(cols)

    def _change(curr, prev_val):
        if prev_val == 0:
            return "—"
        delta_pct = ((curr - prev_val) / prev_val) * 100
        return f"{'↑' if delta_pct > 0 else '↓'} {abs(delta_pct):.0f}%"

    pdf.table_row([("Total Incidents", 50), (str(total), 35), (str(prev_total), 35), (_change(total, prev_total), 30)])
    pdf.table_row([("Hours Lost", 50), (f"{productivity['total_time_lost_hours']:.1f}", 35), ("—", 35), ("—", 30)])
    pdf.table_row([("Fleet Efficiency", 50), (f"{productivity['fleet_efficiency_pct']:.1f}%", 35), ("—", 35), ("—", 30)])
    pdf.table_row([("Active Hotspots", 50), (str(len(hotspots)), 35), ("—", 35), ("—", 30)])

    pdf.ln(6)
    assessment = await generate_narrative(
        "overall_assessment",
        total_incidents=total, prev_incidents=prev_total,
        fleet_efficiency_pct=productivity["fleet_efficiency_pct"],
        total_time_lost_hours=productivity["total_time_lost_hours"],
        hotspot_count=len(hotspots), recommendations_count=len(recommendations),
    )
    pdf.body_text(assessment)

    # ─── Save PDF ────────────────────────────────────────────────────────────
    filename = f"asb_report_{facility_id}_{month_str}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    logger.info(f"[{facility_id}] report saved: {filepath}")

    # Update monthly_reports table
    await postgres.upsert_monthly_report({
        "facility_id": facility_id,
        "month": month_date,
        "total_incidents": total,
        "total_time_lost_hours": productivity["total_time_lost_hours"],
        "fleet_efficiency_pct": productivity["fleet_efficiency_pct"],
        "hotspot_count": len(hotspots),
        "recommendations_count": len(recommendations),
        "report_url": filepath,
    })

    return filepath
